version: "2"
volumes:
  web-author-data:
services:
  nginx:
    image: nginx
    volumes:
      - ./load-balancer.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  web-author-1:
    build: web-author-with-config
    volumes:
     - ./license.properties:/usr/local/tomcat/work/Catalina/localhost/oxygen-xml-web-author/license.properties
    environment:
     - BACKEND_ID=wa1
     - ADMIN_PAGE_IS_DISABLED=true
  web-author-2:
    build: web-author-with-config
    volumes:
     - ./license.properties:/usr/local/tomcat/work/Catalina/localhost/oxygen-xml-web-author/license.properties
    environment:
     - BACKEND_ID=wa2
     - ADMIN_PAGE_IS_DISABLED=true
